### PR TITLE
Add change to makefile to enable device tests

### PR DESCRIPTION
**Pull request by tj-devel709**
I believe that these lines were added to temporarily disable device tests which we would like to turn back on.

Running `make all` in binding-tools-for-swift/tests/tom-swifty-test before reversing the comments gives these results: https://gist.github.com/tj-devel709/7ce6798059ceba7b9c0f0a3eb02c223b#file-gistfile1-txt-L4689

Running after these changes produces these tests results: https://gist.github.com/tj-devel709/987d38d4cfef27a1de5a2dc54a1a98e5#file-gistfile1-txt-L6211

### CODE REVIEW

**Comment by chamons** [comment]
build

**Review by whitneyschmidt — APPROVED** [review]

**Comment by tj-devel709** [comment]
build

**Review by mandel-macaque — APPROVED** [review]
Looks ok, but needs to get fixed.

**Comment by tj-devel709** [comment]
These changes plus more got merged in this [PR](https://github.com/xamarin/binding-tools-for-swift/pull/505)

**Pull request closed without merging**
